# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.5.1

clone:
  depth: full
pipelines:
  default:
    - step:
        name: Build The Application
        caches:
          - pip
        script: 
          - pip install virtualenv
          - virtualenv swapleenv
          - source swapleenv/bin/activate
          - pip install -r requirements.txt
    - step:
        name: Deploy to Test
        deployment: test
        script:
          - echo "Unit Test Checking"
          - echo "Code Coverage Test"
    - step:
        name: Deploy to Production
        deployment: production
        trigger: manual
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
 

